worker_processes 1;

events {
    worker_connections 1024;
}


http {
    include mime.types;

    upstream nodejs_cluster {
        server 127.0.0.1:4001;
        server 127.0.0.1:4002;
        server 127.0.0.1:4003;
    }
    
    server {
        listen 443 ssl; 
        
        ssl_certificate /home/hymndrazill/nginx-certs/nginx-selfsigned.crt;
        ssl_certificate_key /home/hymndrazill/nginx-certs/nginx-selfsigned.key;

        server_name localhost;

        location / {
            proxy_pass http://nodejs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
    
    }
}